apiVersion: apps/v1
kind: Deployment
metadata:
  name: packaginganddeliverydepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PackagingAndDelivery
  template:
    metadata:
      labels:
        app: PackagingAndDelivery
    spec:
      containers:
      - name: packaginganddelivery
        image: returnorderrn1.azurecr.io/packagerepos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: packagesn

---
apiVersion: v1
kind: Service
metadata:
  name: packaginganddelivery
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PackagingAndDelivery
