apiVersion: apps/v1
kind: Deployment
metadata:
  name: packaginganddeliverydepl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: PackagingAndDelivery
  template:
    metadata:
      labels:
        app: PackagingAndDelivery
    spec:
      containers:
      - name: packaginganddelivery
        image: returnorderimages.azurecr.io/packagaingpos:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: packagingsn

---
apiVersion: v1
kind: Service
metadata:
  name: packaginganddelivery
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: PackagingAndDelivery
